### ISSUE TITLE
lag with multiple players rendered/many players on tab list

### ISSUE THREAD

**Issue by robinowow** [orifu/skin-overrides#1]
while using the mod, there is lag, increasing with players rendered. looking at tab with many players also creates lag. 
both cases of this lag are unaffected by whether i am using custom skins for the players rendered/in tab

**Comment by orifu** [comment]
hi thanks for the report! i was unsure if there would be performance problems with more players online. i will make optimisations for the 2.1.0 release. until then, you can disable the mod

**Comment by orifu** [comment]
i think this issue is now resolved and im planning to release 2.1.0 soon. if you tell me which version of minecraft you're using, i can send you a new jar and you can test to see if it's any better, but from my testing (50 fake players in a void world):

without the mod:
![an fps graph, consistently staying at 60fps](https://github.com/orifu/skin-overrides/assets/70169300/3bec5b0d-6755-452d-bd8b-27dce284c20c)
with 2.0.0:
![another fps graph, with a more inconsistent frame rate](https://github.com/orifu/skin-overrides/assets/70169300/7d7fcc65-b426-417d-a8a1-ad272bd2e16f)
with 2.1.0:
![a third fps graph, which is also consistently at 60fps](https://github.com/orifu/skin-overrides/assets/70169300/d3e3ab3a-9793-4192-9cd5-e2be5b41c6fc)

**Comment by robinowow** [comment]
sure, im using 1.20.4

**Comment by orifu** [comment]
[skin_overrides-2.1.0-beta+1.20.4.zip](https://github.com/user-attachments/files/16113863/skin_overrides-2.1.0-beta%2B1.20.4.zip)

**Comment by robinowow** [comment]
yeah the lag is completely gone now except for when loading new players 
however, i notice that when unloading a player and then rendering them (by coming close to them), i get lagspikes:
![image](https://github.com/orifu/skin-overrides/assets/174745916/1c0cb1c4-8f34-4080-b019-c0061dfdd8a1)
tab menu also seems a little laggier, though not really by a noticeable amount:
![image](https://github.com/orifu/skin-overrides/assets/174745916/18e07153-faa7-4e0e-9e2f-54a208e36603)
^ where i am opening tab menu ~midway through the fps graph
opening tab for the first time also creates lag, which dissipates the longer i hold it down (i assume as players are being cached?)

**Comment by robinowow** [comment]
![image](https://github.com/orifu/skin-overrides/assets/174745916/f42043e6-b1f2-4876-b669-569d6ef38df5)
capes and skins in their respective libraries appear to be broken as well, they are overlayed on top of each other

**Comment by orifu** [comment]
> however, i notice that when unloading a player and then rendering them (by coming close to them), i get lagspikes

> opening tab for the first time also creates lag

ive done a quick check and im not sure if the mod would be causing either of these issues. do they occur on vanilla?

> capes and skins in their respective libraries appear to be broken as well

ah thanks, i rewrote a lot of the ui stuff to support 11 different versions so it's not surprising i made a goof

**Comment by robinowow** [comment]
> ive done a quick check and im not sure if the mod would be causing either of these issues. do they occur on vanilla?

disabled some recently added mods, one of them was the issue, thats my bad
yeah theres no lag at all

**Comment by orifu** [comment]
okay thanks for checking! it really helps a lot <3

**Comment by orifu** [comment]
i've released 2.1.0 now, so i'm going to close this issue!
